version: '3.8'

services:

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: gerenciador-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço da Aplicação Spring Boot
  app:
    build:
      context: ./backend
    container_name: gerenciador-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true

  # Serviço do Frontend React
  frontend:
    build:
      context: ./frontend
    container_name: sales-frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  postgres-data: