name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test and Verify Coverage with Maven
        run: mvn -B verify --file backend/pom.xml

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          # CORREÇÃO: Explicitamente definimos o tipo de autenticação
          auth-type: 'servicePrincipal' 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Build and Push Docker image'
        run: |
          docker build ./backend -t ${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gerenciador-backend' # O nome do seu App Service
          images: '${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}'
          
      - name: 'Logout from Azure'
        run: |
          az logout
          az cache purge
          az account clear