name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test and Verify Coverage with Maven
        run: mvn -B verify --file backend/pom.xml

  deploy:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: validate

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR (via Azure CLI identity)
        run: az acr login --name gerenciadorapp

      - name: Docker Build and Push
        run: |
          docker build \
            --progress=plain \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            ./backend \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}

      - name: Deploy to App Service (using ACR image)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gerenciador-backend'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/gerenciador-backend:${{ github.sha }}'
