name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, Test and Verify Coverage with Maven
        run: mvn -B verify --file backend/pom.xml

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Placeholder para o Deploy
        run: |
          echo "Iniciando o deploy para o ambiente de produção..."
          echo "Aqui entrariam os passos para construir a imagem Docker e enviar para a nuvem."
          echo "Deploy concluído com sucesso (simulação)."